# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReglog():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reglog(self):
    self.driver.get("https://demo.guru99.com/test/newtours/")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.LINK_TEXT, "REGISTER").click()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Dylan")
    self.driver.find_element(By.NAME, "lastName").send_keys("Gill")
    self.driver.find_element(By.NAME, "phone").send_keys("9051231988")
    self.driver.find_element(By.ID, "userName").send_keys("dylangill@hotmail.com")
    self.driver.find_element(By.NAME, "address1").send_keys("123 juliet road")
    self.driver.find_element(By.NAME, "city").send_keys("Oshawa")
    self.driver.find_element(By.NAME, "state").send_keys("Ontario")
    self.driver.find_element(By.NAME, "postalCode").send_keys("L1R 1W2")
    self.driver.find_element(By.NAME, "country").click()
    dropdown = self.driver.find_element(By.NAME, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'CANADA']").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("dylanthethrill")
    self.driver.find_element(By.NAME, "password").send_keys("school")
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("school")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "sign-in").click()
    self.driver.find_element(By.NAME, "userName").click()
    self.driver.find_element(By.NAME, "userName").send_keys("dylanthethrill")
    self.driver.find_element(By.NAME, "password").send_keys("school")
    self.driver.find_element(By.NAME, "submit").click()
  
