# Name: Dylan Gill and Shahmeir Shaikh
# Filename: TestBankingProject.py
# Date: April 10th, 2024
# Description: Menu driven program that automatically run tests for the banking website at your command.

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Customized statement
class TestBankingAuto():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()

    def test_custom_statement(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Customised Statement").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("133593")
        self.driver.find_element(By.NAME, "fdate").click()
        self.driver.find_element(By.NAME, "fdate").send_keys("0002-04-07")
        self.driver.find_element(By.NAME, "fdate").send_keys("0020-04-07")
        self.driver.find_element(By.NAME, "fdate").send_keys("0202-04-07")
        self.driver.find_element(By.NAME, "fdate").send_keys("2024-04-07")
        self.driver.find_element(By.NAME, "tdate").click()
        self.driver.find_element(By.NAME, "tdate").send_keys("0002-04-02")
        self.driver.find_element(By.NAME, "tdate").send_keys("0020-04-02")
        self.driver.find_element(By.NAME, "tdate").send_keys("0202-04-02")
        self.driver.find_element(By.NAME, "tdate").send_keys("2025-04-02")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) > td:nth-child(2)").click()
        self.driver.find_element(By.NAME, "amountlowerlimit").click()
        self.driver.find_element(By.NAME, "amountlowerlimit").send_keys("1")
        self.driver.find_element(By.NAME, "numtransaction").click()
        self.driver.find_element(By.NAME, "numtransaction").send_keys("2")
        self.driver.find_element(By.NAME, "amountlowerlimit").click()
        self.driver.find_element(By.NAME, "amountlowerlimit").send_keys("1000")
        self.driver.find_element(By.NAME, "AccSubmit").click()
        self.driver.close 

    # Balance
    def test_balance(self):
        self.driver.quit()
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Balance Enquiry").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("133593")
        self.driver.find_element(By.NAME, "AccSubmit").click()

    # Delete Account
    def test_del_account(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Delete Account").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("133593")
        self.driver.find_element(By.NAME, "AccSubmit").click()
        assert self.driver.switch_to.alert.text == "Do you really want to delete this Account?"
        self.driver.switch_to.alert.accept()

    # Delete Customer
    def test_del_customer(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Delete Customer").click()
        self.driver.find_element(By.NAME, "cusid").click()
        self.driver.find_element(By.NAME, "cusid").send_keys("55624")
        self.driver.find_element(By.NAME, "AccSubmit").click()
        assert self.driver.switch_to.alert.text == "Do you really want to delete this Customer?"
        self.driver.switch_to.alert.accept()

    # Edit Account 
    def test_edit_account(self):
        self.driver.get("https://demo.guru99.com/V4/manager/AccCreateMsg.php?aid=133593")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Edit Account").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("133593")
        self.driver.find_element(By.NAME, "AccSubmit").click()

    # Edit Customer
    def test_edit_customer(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Edit Customer").click()
        self.driver.find_element(By.NAME, "cusid").click()
        self.driver.find_element(By.NAME, "cusid").send_keys("55624")
        self.driver.find_element(By.NAME, "AccSubmit").click()
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("whise")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys("asds")
        self.driver.find_element(By.NAME, "sub").click()


    # Mini Statement 
    def test_mini(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "Mini Statement").click()
        self.driver.find_element(By.NAME, "accountno").click()
        self.driver.find_element(By.NAME, "accountno").send_keys("133593")
        self.driver.find_element(By.NAME, "AccSubmit").click()

    # New Account 
    def test_new_account(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "New Account").click()
        self.driver.find_element(By.NAME, "cusid").click()
        self.driver.find_element(By.NAME, "cusid").send_keys("30160")
        self.driver.find_element(By.NAME, "inideposit").click()
        self.driver.find_element(By.NAME, "inideposit").send_keys("123456")
        self.driver.find_element(By.NAME, "button2").click()

    # New Customer
    def test_new_customer(self):
        self.driver.get("https://demo.guru99.com/V4/manager/Managerhomepage.php")
        self.driver.set_window_size(1056, 802)
        self.driver.find_element(By.LINK_TEXT, "New Customer").click()
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("asasqd")
        self.driver.find_element(By.ID, "dob").click()
        self.driver.find_element(By.NAME, "addr").click()
        self.driver.find_element(By.NAME, "addr").send_keys("sdwasdw")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("whis")
        self.driver.find_element(By.ID, "dob").click()
        self.driver.find_element(By.ID, "dob").send_keys("2024-04-02")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys("asd")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("234567")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(By.NAME, "telephoneno").send_keys("234541345")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys("saxc@email.com")
        self.driver.find_element(By.NAME, "password").send_keys("pokemon1")
        self.driver.find_element(By.NAME, "sub").click()

    # Menu to run test modules
    def menu(self):
        print("\nSelect a Test Method to excecute below.")
        print("1. New Customer")
        print("2. Edit Customer")
        print("3. Delete Customer")
        print("4. New Account")
        print("5. Edit Account")
        print("6. Delete Account")
        print("7. Balance Enquiry")
        print("8. Mini Statement")
        print("9. Customized Statement")

        choice = input("Enter your choice from 1-9: ")
        if choice not in ['1', '2', '3', '4', '5', '6', '7', '8', '9']:
                print("\n!ERROR!, Please enter a numeric character between 1-9!")
                return

        if choice == '1':
            self.test_new_customer()
        if choice == '2':
            self.test_edit_customer()
        if choice == '3':
            self.test_del_customer()
        if choice == '4':
            self.test_new_account()
        if choice == '5':
            self.test_edit_account()
        if choice == '6':
            self.test_del_account()
        if choice == '7':
            self.test_balance
        if choice == '8':
            self.test_mini()
        if choice == '9':
            self.test_custom_statement()

if __name__ == "__main__":
    test_obj = TestBankingAuto()
    test_obj.menu()